places_list = ['Italy', 'Germany', 'South Korea', 'Taiwan', 'Moon']
print(places_list)
print(sorted(places_list))
print(sorted(places_list, reverse=True))
places_list.reverse()
print(places_list)
places_list.reverse()
print(places_list)
places_list.sort()
print(places_list)
places_list.sort(reverse=True)
print(places_list)

print("The first three items in this list are: ")
print(places_list[:3])
print("Three items from the middle of the list are: ")
print(places_list[1:4])
print("The last three items in the list are: ")
print(places_list[-3:])
